using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class StopScriptDuringAnimation : MonoBehaviour
{
    public Animator externalAnimator;
    private SpriteRenderer spriteRenderer;
    private HandFollowMouse handFollowMouse;

    private void Awake()
    {
        // "Player" ｿﾀｺ・ｧﾆｮｿ｡ｼｭ Animator ﾄﾄﾆｳﾍﾆｮｸｦ ｰ｡ﾁｮｿﾉｴﾏｴﾙ.
        GameObject playerObject = GameObject.Find("Player");
        if (playerObject != null)
        {
            externalAnimator = playerObject.GetComponent<Animator>();

            // externalAnimatorｰ｡ ﾁｸﾀ酩ﾏｴﾂﾁ・ｴﾙｽﾃ ﾈｮﾀﾎﾇﾕｴﾏｴﾙ.
            if (externalAnimator == null)
            {
                Debug.LogError("Player ｿﾀｺ・ｧﾆｮｿ｡ Animator ﾄﾄﾆｳﾍﾆｮｰ｡ ｾｽﾀｴﾏｴﾙ!");
            }
        }
        else
        {
            Debug.LogError("\"Player\" ｿﾀｺ・ｧﾆｮｸｦ ﾃ｣ﾀｻ ｼ・ｾｽﾀｴﾏｴﾙ!");
        }

        // ﾇﾀ・ｿﾀｺ・ｧﾆｮｿ｡ｼｭ SpriteRendererｿﾍ HandFollowMouse ﾄﾄﾆｳﾍﾆｮｸｦ ｰ｡ﾁｮｿﾉｴﾏｴﾙ.
        spriteRenderer = GetComponent<SpriteRenderer>();
        handFollowMouse = GetComponent<HandFollowMouse>();

        // ﾄﾄﾆｳﾍﾆｮｰ｡ ﾁｸﾀ酩ﾏｴﾂﾁ・ﾈｮﾀﾎﾇﾕｴﾏｴﾙ.
        if (spriteRenderer == null)
        {
            Debug.LogError("SpriteRenderer ﾄﾄﾆｳﾍﾆｮｰ｡ ｾｽﾀｴﾏｴﾙ!");
        }
        if (handFollowMouse == null)
        {
            Debug.LogError("HandFollowMouse ﾄﾄﾆｳﾍﾆｮｰ｡ ｾｽﾀｴﾏｴﾙ!");
        }
    }

    // Updateｴﾂ ｸﾅ ﾇﾁｷｹﾀﾓｸｶｴﾙ ﾈ｣ﾃ箏ﾋｴﾏｴﾙ.
    void Update()
    {
        // Animatorﾀﾇ ﾇﾀ・ｻﾅﾂｸｦ ﾈｮﾀﾎﾇﾕｴﾏｴﾙ.
        if (externalAnimator != null && spriteRenderer != null && handFollowMouse != null)
        {
            if (externalAnimator.GetCurrentAnimatorStateInfo(0).IsName("Start"))
            {
                handFollowMouse.enabled = false;
                spriteRenderer.enabled = false;
            }
            else
            {
                handFollowMouse.enabled = true;
                spriteRenderer.enabled = true;
            }
        }
    }
}
